[project]
name = "radlermass"
version = "0.1.0"
description = "Go binaries in Python wheels."
readme = "README.md"
license = "MIT OR Apache-2.0"
license-files = ["LICENSE-APACHE", "LICENSE-MIT"]
authors = [
    { name = "William Woodruff", email = "william@yossarian.net" }
]
requires-python = ">=3.14"
dependencies = [
    "packaging>=26.0",
]

[project.scripts]
radlermass = "radlermass._cli:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest",
    "ruff",
    "ty",
]

[tool.uv.workspace]
members = []

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM", "PT"]

[tool.pytest.ini_options]
testpaths = ["tests"]
